# Generated by Django 3.1.4 on 2021-04-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20210420_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselmodel',
            name='carousel_image',
            field=models.ImageField(default='placeholder-image.png', upload_to='project_images/carousel_images/'),
        ),
        migrations.AlterField(
            model_name='frontmodel',
            name='front_image',
            field=models.ImageField(default='placeholder-image.png', upload_to='project_images/front_images/'),
        ),
        migrations.AlterField(
            model_name='projectchildmodel',
            name='project_child_image',
            field=models.ImageField(default='placeholder-image.png', upload_to='project_images/child_images/'),
        ),
    ]
