# Generated by Django 3.1.4 on 2021-03-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectchildmodel',
            name='project_child_link',
        ),
        migrations.RemoveField(
            model_name='projectmainmodel',
            name='project_main_link',
        ),
    ]
