# Generated by Django 3.1.4 on 2021-04-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210328_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_name', models.CharField(max_length=60)),
                ('carousel_image', models.ImageField(upload_to='project_images/carousel_images/')),
            ],
        ),
    ]
