# Generated by Django 3.1.4 on 2021-04-08 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_frontmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontmodel',
            old_name='project_main',
            new_name='front_main',
        ),
    ]
