# Generated by Django 3.1.4 on 2021-04-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210419_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmainmodel',
            name='project_main_image',
            field=models.ImageField(default='images/placeholder-image.png', upload_to='project_images/main_images/'),
        ),
    ]
