# Generated by Django 3.1.4 on 2021-04-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210419_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmainmodel',
            name='project_main_image',
            field=models.ImageField(default='placeholder-image.png', upload_to='project_images/main_images/'),
        ),
    ]
