# Generated by Django 3.1.4 on 2021-04-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20210420_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('project_image', models.ImageField(default='placeholder-image.png', upload_to='product_images/')),
                ('product_description', models.CharField(max_length=100)),
            ],
        ),
    ]
